### PR TITLE
updated npm deprecated packages

### PR DESCRIPTION
**Pull request by evam3illinois**

### CODE REVIEW

**Review by angrave — CHANGES_REQUESTED** [review]
There are no files in this commit!?
Did you forget to add requirements.txt?

**Comment by evam3illinois** [comment]
I had problems with the commit. What I changed was the package.json. I will try to commit it again with the new changes.

Enviado desde mi iPad

El nov. 4, 2022, a las 14:07, Lawrence Angrave ***@***.***> escribió:

﻿

@angrave requested changes on this pull request.

There are no files in this commit!?
Did you forget to add requirements.txt?

**Comment by angrave** [comment]
CI Build is broken.I believe this is something you can reproduce locally?

2022-11-07T17:32:42.6483533Z Expected plugin to either be a plugin instance or a { name, config } object but found @electron-forge/plugin-webpack,[object Object]
2022-11-07T17:32:42.6484482Z Error: Expected plugin to either be a plugin instance or a { name, config } object but found @electron-forge/plugin-webpack,[object Object]
2022-11-07T17:32:42.6485366Z     at /home/runner/work/CTCast/CTCast/node_modules/@electron-forge/core/dist/util/plugin-interface.js:39:19
2022-11-07T17:32:42.6486188Z     at Array.map (<anonymous>)
2022-11-07T17:32:42.6486969Z     at new PluginInterface (/home/runner/work/CTCast/CTCast/node_modules/@electron-forge/core/dist/util/plugin-interface.js:21:44)
2022-11-07T17:32:42.6487710Z     at Object._default [as default] (/home/runner/work/CTCast/CTCast/node_modules/@electron-forge/core/dist/util/forge-config.js:157:43)
2022-11-07T17:32:42.6488322Z     at async /home/runner/work/CTCast/CTCast/node_modules/@electron-forge/core/dist/api/make.js:64:23

**Comment by angrave** [comment]
Please can you rebase on the current staging branch and do a new PR? Be sure to preserve any remote changes; don't just overwrite everything with your local changes.
(you will need to fetch or pull the staging branch to get the changes locally).

**Pull request closed without merging**
