### PR TITLE
Shortcut

### PR DESCRIPTION
**Pull request by HanBoyou**

### CODE REVIEW

**Comment by angrave** [comment]
Please rebase on current staging and push

**Comment by angrave** [comment]
Tests fails-
```sh
2022-10-31T16:51:52.4665800Z Running 7 tests using 1 worker
2022-10-31T16:51:58.2551710Z Parsing Electron app in /Users/runner/work/CTCast/CTCast/out/ctcast-darwin-x64
2022-10-31T16:52:10.8818050Z ·Promise { [36m<pending>[39m }
2022-10-31T16:52:49.5811980Z ···TParsing Electron app in /Users/runner/work/CTCast/CTCast/out/ctcast-darwin-x64
2022-10-31T16:52:52.8522480Z ··
2022-10-31T16:52:52.8623300Z 
2022-10-31T16:52:52.8726250Z   1) basic_tests.spec.ts:186:1 › renders the file upload page ======================================
2022-10-31T16:52:52.8757910Z 
2022-10-31T16:52:52.8758920Z     [31mTest timeout of 30000ms exceeded.[39m
2022-10-31T16:52:52.8759390Z 
2022-10-31T16:52:52.8761170Z     page.waitForEvent: Timeout 30000ms exceeded while waiting for event "framenavigated"
2022-10-31T16:52:52.8763060Z     =========================== logs ===========================
2022-10-31T16:52:52.8763740Z     waiting for event "framenavigated"
2022-10-31T16:52:52.8764610Z     ============================================================
2022-10-31T16:52:52.8765820Z 
2022-10-31T16:52:52.8766250Z       187 |   page = await electronApp.firstWindow()
2022-10-31T16:52:52.8766860Z       188 |   const [window] = await Promise.all([
2022-10-31T16:52:52.8767700Z     > 189 |     page.waitForEvent('framenavigated'),
2022-10-31T16:52:52.8768400Z           |          ^
2022-10-31T16:52:52.8769230Z       190 |     page.locator('a:has-text("File Upload")').click()
2022-10-31T16:52:52.8769630Z       191 |   ]);
2022-10-31T16:52:52.8770110Z       192 |   await window.waitForSelector('h1')
2022-10-31T16:52:52.8770320Z 
2022-10-31T16:52:52.8771750Z         at /Users/runner/work/CTCast/CTCast/testing/basic_tests.spec.ts:189:10
2022-10-31T16:52:52.8773940Z         at /Users/runner/work/CTCast/CTCast/node_modules/@playwright/test/lib/workerRunner.js:426:9
2022-10-31T16:52:52.8774590Z         at TestInfoImpl._runFn (/Users/runner/work/CTCast/CTCast/node_modules/@playwright/test/lib/testInfo.js:166:7)
2022-10-31T16:52:52.8776160Z         at /Users/runner/work/CTCast/CTCast/node_modules/@playwright/test/lib/workerRunner.js:376:26
2022-10-31T16:52:52.8778080Z         at TimeoutRunner.run (/Users/runner/work/CTCast/CTCast/node_modules/playwright-core/lib/utils/timeoutRunner.js:53:14)
2022-10-31T16:52:52.8779640Z         at TimeoutManager.runWithTimeout (/Users/runner/work/CTCast/CTCast/node_modules/@playwright/test/lib/timeoutManager.js:73:7)
2022-10-31T16:52:52.8780740Z         at TestInfoImpl._runWithTimeout (/Users/runner/work/CTCast/CTCast/node_modules/@playwright/test/lib/testInfo.js:154:26)
2022-10-31T16:52:52.8781720Z         at WorkerRunner._runTest (/Users/runner/work/CTCast/CTCast/node_modules/@playwright/test/lib/workerRunner.js:356:5)
2022-10-31T16:52:52.8782750Z         at WorkerRunner.runTestGroup (/Users/runner/work/CTCast/CTCast/node_modules/@playwright/test/lib/workerRunner.js:218:11)
2022-10-31T16:52:52.8783620Z         at process.<anonymous> (/Users/runner/work/CTCast/CTCast/node_modules/@playwright/test/lib/worker.js:88:5)
2022-10-31T16:52:52.8783940Z 
2022-10-31T16:52:52.8784120Z   Slow test file: basic_tests.spec.ts (38s)
2022-10-31T16:52:52.8784550Z   Consider splitting slow test files to speed up parallel execution
2022-10-31T16:52:52.8784770Z 
2022-10-31T16:52:52.8784890Z   1 failed
2022-10-31T16:52:52.8785570Z     basic_tests.spec.ts:186:1 › renders the file upload page =======================================
2022-10-31T16:52:52.8786140Z   6 passed (1m)
```

**Review by angrave — COMMENTED** [review]
The raw logs of recent github actions are available for ~ a day in the 
https://github.com/grainger-illinois/CTCast/actions

Do you need help debugging this build error?
Did you git pull, rebase your branch with the latest from staging and then git push?

**Comment by HanBoyou** [comment]
Sorry for not responding in time. I just met with Timmy (responsible for the testcases) today and will update on this issue tomorrow. Should be just a few tweaks on the playwright test cases.

**Pull request merged**
